name: Publish SNAPSHOT versions
on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete previous SNAPSHOT packages
        uses: credible-team/action-version-cleaner@v1.0.0
        with:
          package-type: maven
          version-tag: 0.0.0-SNAPSHOT
          is-version-tag-strict: false
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish new SNAPSHOT package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Pversion=0.0.0-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
