name: Publish SNAPSHOT versions
on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
env:
  VERSION_TAG: SNAPSHOT
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete SNAPSHOT packages
        uses: credible-team/action-version-cleaner@main
        with:
          github-repository: ${{ github.repository }}
          package-type: maven
          version-tag: $VERSION_TAG
          github-token: ${{ secrets.WRITE_DELETE_PACKAGES_TOKEN }}

      - name: Publish SNAPSHOT package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
