name: Publish SNAPSHOT versions
on:
  push:
    branches: ['main']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.8.0

      - name: List All Packages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          OWNER=credible-team
          REPO=gradle-versions
          
          # List all packages in the repository using the GitHub API
          RESPONSE=$(curl -u $GH_TOKEN:x-oauth-basic "https://api.github.com/repos/$OWNER/packages")
          echo "Response: $RESPONSE"
          # Check if the response contains packages
          if [[ $(echo "$RESPONSE" | jq '. | length') -gt 0 ]]; then
            # Filter packages based on repository.name
            PACKAGES=$(echo "$RESPONSE" | jq -r '.[] | select(.repository.name == $REPO) | .name')
          
            # Check if there are packages to delete
            if [ -n "$PACKAGES" ]; then
              echo "Packages to delete: $PACKAGES"
          
              # Loop through and delete each package
              for PACKAGE_NAME in $PACKAGES; do
                echo "Deleting package: $PACKAGE_NAME"
                curl -X DELETE -u $GH_TOKEN:x-oauth-basic "https://maven.pkg.github.com/$OWNER/$PACKAGE_NAME"
              done
            else
              echo "No packages found in the 'gradle-versions' repository."
            fi
          else
            echo "No packages found in the GitHub Packages account."
          fi

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
